vpc:
  maxAzs: 2
  natGateways: 0
  ipv6enabled: true
alb:
  listener:
    certificateArn: "arn:aws:acm:ap-northeast-1:340227574277:certificate/2e0c79e2-c141-4896-bbd7-4cef6775b314" # .9incloud.com
  targetHealthCheck: 
    enabled: true
    interval: 30 # unit: seconds
    path: "/hello"
    timeout: 5 # unit: seconds
    healthyThresholdCount: 5
    unhealthyThresholdCount: 2
  deregistrationDelay: 60 # unit: seconds